set -g mouse on
set -g history-limit 50000
set -g base-index 1
setw -g pane-base-index 1
set -sg escape-time 10
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

# drag to select without auto-copying or clearing the selection
bind -T copy-mode    MouseDragEnd1Pane send-keys -X stop-selection
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X stop-selection
