views:
  # Alters the pod view column layout. Uses GVR as key
  v1/pods:
    # Overrides default sort column
    sortColumn: AGE:asc
    columns:
      - NAME
      - STATUS
      - NAMESPACE
      - READY
      - RESTARTS
      - MEM/R
      - MEM/L
      - NODE
      - AGE
      - PF
      - CPU
      - MEM
      - CPU/R
      - CPU/L
      # - IP

  # # Alters the service view column layout
  # v1/services:
  #   sortColumn: AGE:dec
  #   columns:
  #     - AGE
  #     - NAMESPACE
  #     - NAME
  #     - TYPE
  #     - CLUSTER-IP
